blog/urls.py
from django.urls import path
from django.shortcuts import render
from django.http import HttpResponse


from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
 
]

gollek_group/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Usermasuk (models.Model):
    nama_user_masuk = models.ForeignKey(User, on_delete=models.CASCADE,related_name='semua_user_masuk')
    poto_profil     = models.ImageField(upload_to='profil/', default='', null=True, blank=True)
    email           = models.EmailField(max_length=254)
    jenis_kelamin   = models.CharField(max_length=10)

    def __str__(self):
        return str(self.nama_user_masuk)
    

class Post(models.Model):
    nama          = models.ForeignKey(Usermasuk, on_delete=models.CASCADE, related_name='semua_postingan')
    status        = models.TextField()
    gambar        = models.ImageField(upload_to='images/', default='', null=True, blank=True)
    waktu_posting = models.DateTimeField(auto_now=True, auto_now_add=False)
    def __str__(self):
        return str(self.nama)
    

blog/views.py
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import Http404
from .models import Post, Usermasuk
# Create your views here.

def index(request):
    posts = Post.objects.all();
    usermasuks = Usermasuk.objects.all();
    
    context = {
        'title':'index',
        'posts':posts,
        'user_masuk':usermasuks
    }

    return render(request,'blog/index.html',context)

def login_view(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password= password)

        if user:
            login(request,user)
            return redirect('/')
            
        else:
            messages.add_message(request,messages.INFO,'Username and password yang anda Masukkan salah' )
            return redirect('/login/')
    

    return render(request,'blog/login.html',context={})

@login_required
def logout_view(request):
    context = {
        'title':'Logout'
    }
    if request.method == 'POST':
        keluar = request.POST.get('keluar')
        if keluar:
            logout(request)
            return redirect('blog:login_view')
            
    return render(request,'blog/logout.html',context)

blog/templates/blog/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style/css/style2.css' %}">
    <title>Document</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand ">
        <div class="navbar-brand">
            <img width="70px" src="{% static 'logo/best.jpg' %}" alt="">
        </div>
        <div>
            {% for usr in user.semua_user_masuk.all  %}
                <p>{{usr.nama_user_masuk}}</p>
                <img width="40px" src="{{usr.poto_profil.url}}" alt="">
            {% endfor %}
        </div>
        <ul class="navbar-nav margin-auto ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'blog:index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link tombol" href="{% url 'blog:logout_view' %}">Logout</a></li>
            {% else %}
            <li class="nav-item ml-lg-4"><a class="nav-link tombol" href="{% url 'blog:login_view' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav><br>
    <div class="jumbotron">
        <h1>Selamat Datang {{user}} di Django</h1>
    </div>
    <div class="container">
        
        {% for post in posts  %}
            <h2>{{post.nama}}</h2>
            <p>{{post.status}}</p>
            <p>{{post.waktu_posting}}</p>
        {% endfor %}
            
    </div>  
</div>

    
</body>
</html>

blog/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    
    {% if messages %}
        
        {% for msg in messages  %}
        <h1>{{msg}}</h1>    
        {% endfor %}
        
    {% endif %}
        
    <form method="POST">
        {% csrf_token %}
        <label for="">Usernama</label><br>
        <input type="text" name="username"><br><br>
        <label for="">Password</label><br>
        <input type="password" name="password"><br><br>
        <input type="submit" value="Login">
    </form>
</body>
</html>

blog/templates/blog/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <h1>{{title}}</h1>
    <h2>Klick For Logout</h2>
    <form method="POST">
        {% csrf_token %}
        <input name="keluar" type="submit" value="Logout">
    </form>
</body>
</html>